---
AWSTemplateFormatVersion: '2010-09-09'
Transform: CfnGitSync
Parameters:
  RepositoryOwner:
    Type: String
    Default: ''
  RepositoryName:
    Type: String
    Default: ''
Resources:
  InitialPlaceholder:
    Type: AWS::CloudFormation::WaitConditionHandle
  DevS3bucketStack:
    Type: CfnGitSync::Stack
    Properties:
      RepositoryOwner: "!Ref RepositoryOwner"
      RepositoryName: "!Ref RepositoryName"
      BranchName: main
      StackName: dev-s3-bucket
      StackDeploymentFile: stacks/environments/dev/eu-central-1/s3-bucket.stack.yaml
